add module1
ins21/nodejs-global-mentoring-program pull request #1
Opened 2020-08-17 21:48 UTC by ins21

2020-08-22 12:52 UTC, Vladlan requested changes

2020-08-22 12:52 UTC, Vladlan commented on module1/task1/task1.js
> +readInput.on('line', value => {
![task 1](https://user-images.githubusercontent.com/20605638/90956410-1448e800-e48f-11ea-9490-28ab273d7fc8.PNG)

2020-08-22 12:52 UTC, Vladlan commented on module1/task1/task1.js
> +readInput.on('line', value => {
Make your code work as in task 1.1 description

2020-08-23 17:11 UTC, ins21 commented on module1/task1/task1.js
> +readInput.on('line', value => {
Fixed, thanks.

2020-08-30 16:50 UTC, Vladlan approved these changes

2020-09-06 11:11 UTC, merged